### ISSUE TITLE
Hierarchical captions of raw video data

### ISSUE THREAD

**Issue by G-U-N** [md-mohaiminul/VideoRecap#1]
Awesome work! Hope to know is there any script to predict hierarchical captions of raw video data with the pretrained weights, which would be greatly useful. Thanks in advance.

**Comment by Samge0** [comment]
+1

**Comment by Xuchen-Li** [comment]
+1

**Comment by md-mohaiminul** [comment]
Thanks for your comments. We have added a demo notebook (demo.ipynb) to extract three-levels of hierarchical captions from any video using our pretrained models.
