### ISSUE TITLE
Usage of Pre-Trained Models

### ISSUE THREAD

**Issue by fakerybakery** [md-mohaiminul/VideoRecap#5]
Hello,
Apologies for my ignorance, but how can I use the pre-trained models to caption a video? I see instructions for extracting features, training, and evaluating the model, but I can't figure out how to generate captions.
Thank you!

**Comment by md-mohaiminul** [comment]
Thanks for your comments. We have added a demo notebook (demo.ipynb) to extract three-levels of hierarchical captions from any video using our pretrained models.

**Comment by fakerybakery** [comment]
Cool, thanks so much! Must have missed that, sorry about that!
