### ISSUE TITLE
Question about the training cost

### ISSUE THREAD

**Issue by Richar-Du** [md-mohaiminul/VideoRecap#6]
Thanks for your awesome work! Could you please describe the training costs (the type of GPU and the training time) of the three stages, respectively? Thanks in advance :)

**Comment by md-mohaiminul** [comment]
Hi,
We train our model on 8 V100 GPUs (32 GB memory). Training clip captioning takes ~30 hours, segment description ~5 hours, and video summary ~5 hours.

**Comment by Richar-Du** [comment]
Got it! Thanks for your reply :)
