### ISSUE TITLE
Question about the clip captions generated by the model for my video.

### ISSUE THREAD

**Issue by Xuchen-Li** [md-mohaiminul/VideoRecap#7]
Thank you for the outstanding work. The demo notebook offers a highly convenient method for utilizing the VideoRecap model. However, I've observed that some of the clip captions generated for my video are incomplete, which is also the case with the notebook's processing of "example.mp4", as exemplified by captions like "704.0 708.0 #C C looks at the".
Is this the expected outcome, or might I be misusing the model in some way?

**Comment by md-mohaiminul** [comment]
Hi,
Thanks for your comment. While most clip captions should be complete sentence, sometimes there can be imperfect/incomplete captions like the one you showed. If most of the captions are good, then your model should be fine.

**Comment by Xuchen-Li** [comment]
Thank you for your timely reply, and I wish your scientific research goes smoothly.
